"""The flat-name to grouped-path mapping that keeps documented env vars working.

Every entry maps one **public flat field name** (``HYDE_ENABLED`` /
``hyde_enabled``) to its dotted path in the grouped model
(``retrieval.hyde.enabled``). This table is the backward-compatibility contract
from `docs/adr/037-grouped-configuration-model.md`: flat names are what users
write, grouped paths are how the model is organised.

``tests/test_settings.py`` asserts the mapping is total in both directions, so a
new grouped field cannot be added without giving it a flat name, and a flat name
cannot be dropped silently.
"""

from __future__ import annotations

# flat field name -> dotted path within Settings' grouped sub-models.
FLAT_TO_PATH: dict[str, str] = {
    "ollama_base_url": "ollama.base_url",
    "ollama_embed_model": "ollama.embed_model",
    "ollama_llm_model": "ollama.llm_model",
    "llm_temperature": "llm.temperature",
    "llm_seed": "llm.seed",
    "llm_timeout_seconds": "llm.timeout_seconds",
    "llm_backend": "llm.backend",
    "llm_fallback_backend": "llm.fallback_backend",
    "llm_retry_max_attempts": "llm.retry_max_attempts",
    "llm_circuit_fail_max": "llm.circuit_fail_max",
    "llm_circuit_reset_timeout_seconds": "llm.circuit_reset_timeout_seconds",
    "openai_api_key": "llm.openai_api_key",
    "openai_model": "llm.openai_model",
    "anthropic_api_key": "llm.anthropic_api_key",
    "anthropic_model": "llm.anthropic_model",
    "agent_model": "llm.agent_model",
    "chroma_persist_path": "chroma.persist_path",
    "chroma_collection_name": "chroma.collection_name",
    "chunk_chars": "chunking.chars",
    "chunk_overlap_chars": "chunking.overlap_chars",
    "chunking_mode": "chunking.mode",
    "chunk_max_chars": "chunking.max_chars",
    "chunk_min_chars": "chunking.min_chars",
    "embedding_batch_size": "embedding.batch_size",
    "embedding_provider": "embedding.provider",
    "embedding_timeout_seconds": "embedding.timeout_seconds",
    "sentence_transformers_model": "embedding.sentence_transformers_model",
    "embedding_model": "embedding.model",
    "embedding_cache_path": "embedding.cache_path",
    "embedding_cache_max_entries": "embedding.cache_max_entries",
    "embedding_cache_max_bytes": "embedding.cache_max_bytes",
    "embedding_cache_preprocessing_version": "embedding.cache_preprocessing_version",
    "embedding_cache_task_prefix": "embedding.cache_task_prefix",
    "ingest_recursive": "ingest.recursive",
    "ingest_roots": "ingest.roots",
    "max_pending_ingest_jobs": "ingest.max_pending_jobs",
    "upload_dir": "upload.dir",
    "upload_max_bytes": "upload.max_bytes",
    "upload_retention_seconds": "upload.retention_seconds",
    "upload_quota_bytes": "upload.quota_bytes",
    "audit_log_path": "audit.log_path",
    "audit_log_max_bytes": "audit.log_max_bytes",
    "audit_log_retention_seconds": "audit.log_retention_seconds",
    "audit_log_metadata_only": "audit.log_metadata_only",
    "audit_log_redact_content": "audit.log_redact_content",
    "ocr_enabled": "ocr.enabled",
    "ocr_language": "ocr.language",
    "ocr_min_chars_per_page": "ocr.min_chars_per_page",
    "rag_top_k": "retrieval.top_k",
    "retriever_plugin": "retrieval.plugin",
    "rag_min_context_score": "retrieval.min_context_score",
    "retrieval_mode": "retrieval.mode",
    "bm25_weight": "retrieval.bm25_weight",
    "rrf_k": "retrieval.rrf_k",
    "freshness_half_life_days": "retrieval.freshness_half_life_days",
    "freshness_weight": "retrieval.freshness_weight",
    "parent_expansion_enabled": "retrieval.parent_expansion_enabled",
    "query_rewrite_enabled": "retrieval.query_rewrite_enabled",
    "retrieval_experiment_mode": "retrieval.experiment_mode",
    "rag_system_prompt": "retrieval.system_prompt",
    "query_expansion_enabled": "retrieval.expansion.enabled",
    "query_expansion_max_variants": "retrieval.expansion.max_variants",
    "query_expansion_max_query_chars": "retrieval.expansion.max_query_chars",
    "query_expansion_candidate_budget": "retrieval.expansion.candidate_budget",
    "hyde_enabled": "retrieval.hyde.enabled",
    "hyde_model": "retrieval.hyde.model",
    "hyde_timeout_seconds": "retrieval.hyde.timeout_seconds",
    "hyde_input_max_chars": "retrieval.hyde.input_max_chars",
    "hyde_output_max_chars": "retrieval.hyde.output_max_chars",
    "hyde_output_max_tokens": "retrieval.hyde.output_max_tokens",
    "hyde_lexical_input": "retrieval.hyde.lexical_input",
    "hyde_log_content": "retrieval.hyde.log_content",
    "rerank_enabled": "retrieval.rerank.enabled",
    "rerank_model": "retrieval.rerank.model",
    "rerank_fetch_k": "retrieval.rerank.fetch_k",
    "context_compression_candidate_count": "retrieval.compression.candidate_count",
    "context_compression_max_contexts": "retrieval.compression.max_contexts",
    "context_compression_per_context_tokens": "retrieval.compression.per_context_tokens",
    "context_compression_total_tokens": "retrieval.compression.total_tokens",
    "context_compression_per_context_chars": "retrieval.compression.per_context_chars",
    "context_compression_total_chars": "retrieval.compression.total_chars",
    "context_compression_reserved_prompt_tokens": "retrieval.compression.reserved_prompt_tokens",
    "context_compression_reserved_answer_tokens": "retrieval.compression.reserved_answer_tokens",
    "llm_context_window_tokens": "retrieval.compression.llm_context_window_tokens",
    "adaptive_enabled": "retrieval.adaptive.enabled",
    "adaptive_initial_top_k": "retrieval.adaptive.initial_top_k",
    "adaptive_escalation_top_k": "retrieval.adaptive.escalation_top_k",
    "adaptive_max_rounds": "retrieval.adaptive.max_rounds",
    "adaptive_max_refinements": "retrieval.adaptive.max_refinements",
    "adaptive_max_latency_ms": "retrieval.adaptive.max_latency_ms",
    "adaptive_min_top_score": "retrieval.adaptive.min_top_score",
    "adaptive_min_score_margin": "retrieval.adaptive.min_score_margin",
    "adaptive_min_source_diversity": "retrieval.adaptive.min_source_diversity",
    "adaptive_min_query_coverage": "retrieval.adaptive.min_query_coverage",
    "adaptive_refinement_max_chars": "retrieval.adaptive.refinement_max_chars",
    "adaptive_critique_enabled": "retrieval.adaptive.critique_enabled",
    "adaptive_max_provider_calls": "retrieval.adaptive.max_provider_calls",
    "claim_filter_enabled": "retrieval.claim_filter.enabled",
    "claim_filter_model": "retrieval.claim_filter.model",
    "claim_filter_timeout_seconds": "retrieval.claim_filter.timeout_seconds",
    "claim_filter_input_max_chars": "retrieval.claim_filter.input_max_chars",
    "claim_filter_output_max_tokens": "retrieval.claim_filter.output_max_tokens",
    "claim_filter_log_content": "retrieval.claim_filter.log_content",
    "query_cache_ttl_seconds": "query_cache.ttl_seconds",
    "query_cache_maxsize": "query_cache.maxsize",
    "api_host": "api.host",
    "api_port": "api.port",
    "api_key": "api.key",
    "otel_enabled": "observability.otel_enabled",
    "otel_exporter_endpoint": "observability.exporter_endpoint",
    "otel_service_name": "observability.service_name",
    "otel_sample_rate": "observability.sample_rate",
    "otel_exporter_timeout_seconds": "observability.exporter_timeout_seconds",
    "otel_exporter_retry_count": "observability.exporter_retry_count",
    "otel_capture_content": "observability.capture_content",
    "otel_max_attribute_length": "observability.max_attribute_length",
    "langfuse_enabled": "observability.langfuse_enabled",
}

PATH_TO_FLAT: dict[str, str] = {path: flat for flat, path in FLAT_TO_PATH.items()}

# Flat fields that stay top-level on Settings: they belong to no feature group.
UNGROUPED_FIELDS: frozenset[str] = frozenset({"log_level", "tenant_id", "eval_seed"})
